### ISSUE TITLE
Please consider relicensing this project under MPL 2.0.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/git-auto-updater#1]
Hi. While looking at this new repository, I noticed that the LICENSE file applies GPL 3.0 rather than our employer's standard MPL 2.0. Please consider working with the (all MoCo) committers of this new project to relicense it under MPL – unless there is an external factor that requires a non-MPL license (which does happen occasionally with e.g. Wordpress plugins).

https://www.mozilla.org/en-US/MPL/license-policy/

`New projects which are Mozilla Code may choose either the MPL 2.0 or the Apache License 2.0. No other license is acceptable, because Mozilla is committed to using modern open source licenses with patent grant clauses.`

cc committers @tilmankamp @Cwiiis, licensing @gerv

**Comment by davidflanagan** [comment]
Thanks for pointing this out, Richard. This is @Cwiiis's code, which he originally posted in a personal gitlab repo. It is here in the mozilla repo because gitlab had an outage and we needed the code available right away.

As you point out, the licensing policy is unambiguous. If we host it here, it needs to be MPL or APL. 

Chris: are you willing to change the license to MPL so that we can host this repo here along with the rest of the Vaani repos? If not, I guess we need to go back to your original gitlab repo and update any scripts that reference this one. Note that if we want to eventually integrate all of the vaani client code into a single repo (and I think we should) then we can't use GPL for this piece of it.

**Comment by floatingatoll** [comment]
The Licensing team does make exceptions from time to time if circumstances
demand it - I'm thinking specifically of WordPress plugins, which have a
clearly defined licensing scheme that we must comply with to author
WordPress plugins - but you are probably right that any eventual vaani
client code integration will encounter significant difficulties with
respect to this particular repo.

Both of these points are something you can, if you so desire, discuss at
length with them directly at licensing@m.o - they're far better equipped to
understand and respond to the nuances of your individual situation.

**Comment by gerv** [comment]
If @Cwiiis originally wrote this on his own time, he can choose the licence. If he wrote it on Mozilla time, it needs to be MPL 2.0 or Apache 2.0. (It being in a personal repo or not is not relevant. Mozilla does not require that all code _in_its_repos be MPL 2.0 or Apache 2.0.) Unless you think there's a case for an exception here, in which case someone needs to make it.

Changing the license to match the license policy doesn't require the permission of MoCo/MoFo employees, because their work is owned by Mozilla. 

Does that help?

**Comment by kdavis-mozilla** [comment]
@Cwiiis wrote it on Mozilla time. So I'll change it.

**Comment by kdavis-mozilla** [comment]
Changed to MPL 2.0 in commit [87ba20c](https://github.com/mozilla/git-auto-updater/commit/87ba20c921d24dc17595f877dac84b670a4b3947)

**Comment by Cwiiis** [comment]
The license string also needs to be changed in package.json to 'MPL-2.0'. I'll fix this upstream on Monday.

**Comment by kdavis-mozilla** [comment]
@Cwiiis I'll just do it really quick now
